### ISSUE TITLE
JSR369 adjustments

### ISSUE THREAD

**Issue by klopfdreh** [wildfly/wildfly#10130]
Hi,

just wanted to let you know that the method getPushBuilder of the HttpServletRequest has been renamed to newPushBuilder and a new version of the spec has been released

See:

https://github.com/javaee/servlet-spec/releases

Last version of the undertow-servlet spec has been released on Apr, 2016:

https://mvnrepository.com/artifact/io.undertow/undertow-servlet/2.0.0.Alpha1

It might be good to catch up the changes since I think the release is not that far away anymore.

kind regards

Tobias

**Comment by ctomc** [comment]
it would be better to file issue in https://github.com/undertow-io/undertow repo or even better in jira issue tracker that undertow uses https://issues.jboss.org/browse/UNDERTOW

**Comment by klopfdreh** [comment]
Hi @ctomc - the issue management for the undertow github repo is not enabled. Is there a way to get this activated?
