### ISSUE TITLE
Wildfly and external activemq-artemis instance

### ISSUE THREAD

**Issue by angelorlcosta** [wildfly/wildfly#10360]
Hello all,
 
I am currently working with wildfly 10.0.0.Final and trying to use an external instance of activemq-artemis 2.1.0.
 
Therefore i have configured in artemis file broker.xml an example queue:
```
     <address name="mytestqueue">
            <anycast>
               <queue name="mytestqueue" />
            </anycast>
         </address>
```
 
Then in wildfly i have configured a new pooled-connection-factory under messaging-activemq subsystem:
`<pooled-connection-factory name="activemq-ra-remote" transaction="xa" entries="java:/RemoteJmsXA java:jboss/RemoteJmsXA" connectors="netty-remote-throughput"/>`
 
And also configured the connector:
`<remote-connector name="netty-remote-throughput" socket-binding="messaging-remote-throughput" />`
 
And finally the socket-binding:
```
            <outbound-socket-binding name="messaging-remote-throughput">
                <remote-destination host="localhost" port="61616"/>
            </outbound-socket-binding>
```
 
After all this configured i have deployed my application and right now i am getting an error:
            2017-07-26 15:09:13,702 INFO  [org.apache.camel.component.jms.DefaultJmsMessageListenerContainer] (pool-345-thread-1) Successfully refreshed JMS Connection
          2017-07-26 15:09:18,718 WARN  [org.apache.camel.component.jms.DefaultJmsMessageListenerContainer] (pool-345-thread-2) Setup of JMS message listener invoker failed for destination 'mytestqueue' - trying to recover. Cause: Destination mytestqueue does not exist
 
Any ideas on how i can solve this problem?
 
Thanks in advance,
Ângelo Costa

**Comment by ctomc** [comment]
This is a forum question, as such please create a new discussion in:
https://developer.jboss.org/en/wildfly
