### ISSUE TITLE
cannot run wildfly by launch.sh

### ISSUE THREAD

**Issue by michael2043** [wildfly/wildfly#10410]
I following every step by this video
https://www.youtube.com/watch?v=7ErZpiPglqg
but when I run systemctl restart wildfly in command line ,error happened

wildfly.service - The WildFly Application Server
   Loaded: loaded (/etc/systemd/system/wildfly.service; disabled)
   Active: failed (Result: exit-code) since Tue 2017-08-08 12:37:36 CST; 3s ago
  Process: 5908 ExecStart=/opt/wildfly/bin/launch.sh $WILDFLY_MODE $WILDFLY_CONFIG $WILDFLY_BIND (code=exited, status=1/FAILURE)
 Main PID: 5908 (code=exited, status=1/FAILURE)

Aug 08 12:37:36 localhost.localdomain systemd[1]: Started The WildFly Application Server.
Aug 08 12:37:36 localhost.localdomain systemd[1]: wildfly.service: main process exited, code=exited, status=1/FAILURE
Aug 08 12:37:36 localhost.localdomain systemd[1]: Unit wildfly.service entered failed state.

**Comment by tzelve** [comment]
The error code is not so riched. Can you write back the result of command:
`systemctl status wildfly.service`

Without journal's detailed message i can guess the you forgot to change user that will run the process 
(time 2:40 of video).

**Comment by hargathor** [comment]
Hi,

did you check the ownership in `/opt/wildfly/` ? 

There is a bug in the doc for the systemd. The command should be `chown -R wildfly:wildfly /opt/wildfly/` instead of `chown -R wildfly:wildfly /opt/wildfly/`
