### ISSUE TITLE
Update ASM with Version 5.2

### ISSUE THREAD

**Issue by Tibor17** [wildfly/wildfly#10531]
Currently Arquillian cannot be used together with JaCoCo latest.
The WildFly and Arquillian project should both upgrade the Version of `ASM`.
In POM we have `<version.asm>3.3.1</version.asm>`.
I use these Maven artifacts:
`org.jboss.arquillian.extension:arquillian-jacoco:1.0.0.Alpha9`
`org.jacoco:org.jacoco.core:0.7.9`

**Comment by Tibor17** [comment]
Both libraries ASM and CXF need an upgrade because CXF is dependent on ASM.
If we want to have ASM 5.2 then the first release of CXF which is dependent on ASM 5.2 is CXF 3.2.0 which is the latest one today.
See this issue in WildFly Jira:
https://issues.jboss.org/browse/WFLY-9406

**Comment by bstansberry** [comment]
Thanks for the JIRA. I'm closing this as we don't use github issues. Please see https://github.com/wildfly/wildfly/issues/10310 for why it's even possible to file one against this repo.
