### ISSUE TITLE
OPTIONS Pre Flight is requiring authentication; blocked by 401

### ISSUE THREAD

**Issue by bowlwinkle** [wildfly/wildfly#10565]
I'm not entirely sure if this is a bug or a misconfigured server.

I have an existing server that I did not write.
I am performing a get on a collection which requires basic authentication and since I am adding the Authorization header (and it is cross origin) the browser is sending the pre flight OPTIONS.
The OPTIONS is given a 401 and the browser then does not perform the GET request, which is the problem.  

The expected behavior is that the server, should not require authentication on the pre flight options.  Then, once it responses to the pre flight with it's config, the browser will continue the GET request with the authorization header.

Here is a screen shot of the headers I am sending
![image](https://user-images.githubusercontent.com/2514697/31141313-e7f2fca2-a82b-11e7-9d93-1ed9b075fb87.png)

Here is my filters in the standalone.xml config
```xml
<filters>
            <response-header name="server-header" header-name="Server" header-value="WildFly/9"/>
            <response-header name="x-powered-by-header" header-name="X-Powered-By" header-value="Undertow/1"/>
            <response-header name="Access-Control-Allow-Methods" header-name="Access-Control-Allow-Methods" header-value="GET, POST, OPTIONS, PUT"/>
            <response-header name="Access-Control-Allow-Headers" header-name="Access-Control-Allow-Headers" header-value="Accept, Authorization, Content-Type, x-requested-with"/>
            <response-header name="Access-Control-Allow-Credentials" header-name="Access-Control-Allow-Credentials" header-value="true"/>
</filters>
```

Thanks for your time

**Comment by ctomc** [comment]
wildfly issue tracker is at https://issues.jboss.org/browse/WFLY
