### ISSUE TITLE
Readme. Min Memory in "Using Eclipse" section

### ISSUE THREAD

**Issue by sgwerder** [wildfly/wildfly#10836]
Hi,
In the readme in the "Using Eclipse section it says:

> Make sure Xmx in eclipse.ini is at least 1280M, and it's using Java 8

Shouldn't it read 128M? 1280M seem like an odd number for min memory to me.

**Comment by ctomc** [comment]
no. eclipse wont even start with xmx 128m

**Comment by sgwerder** [comment]
Right. 128M is the minimum memory of the JDK on Windows, I remember. Still, how do you arrive at 1280M? I'm used to power of 2.
