### ISSUE TITLE
inter-app quickstart does not deploy - looks like circular reference problem

### ISSUE THREAD

**Issue by thenulldeveloper** [wildfly/wildfly#11698]
Using Wildfly 14.0.1.Final

When deploying inter-app-appA.war, Wildfly complains about the EJB lookup for:

@EJB(lookup = "java:global/inter-app-appB/BarImpl!org.jboss.as.quickstarts.interapp.shared.Bar")

Likewise, when deploying inter-app-appB.war, Wildfly complains about the EJB lookup for:

@EJB(lookup = "java:global/inter-app-appA/FooImpl!org.jboss.as.quickstarts.interapp.shared.Foo")

To reproduce, from the inter-app quickstart:

mvn install wildfly:deploy

Can also reproduce by just doing an mvn install, then manually deploying the jar, then appA, then appB using the HAL Management Console.

**Comment by thenulldeveloper** [comment]
Thanks. Sorry for not updating the github tracker, but yes, I did notice
this after creating it and I created the following issue in JIRA:

https://issues.jboss.org/browse/WFLY-11084

Regards

**Comment by xstefank** [comment]
Great, thanks! The progress will be tracked in the created JIRA, can you close this issue please?

**Comment by thenulldeveloper** [comment]
Closing, as this is now being tracked in JIRA (WFLY-11084).
