### ISSUE TITLE
Wildfly14.0.0 regression: EL returns empty string on constant

### ISSUE THREAD

**Issue by ArthurBorsboom** [wildfly/wildfly#11705]
This does work in Wildfly 13, but not in Wildfly 14:

```
<%@ page import="com.example.YourConstants" %>
${YourConstants.FOO}
```

**Comment by ArthurBorsboom** [comment]
Done!

https://issues.jboss.org/browse/WFLY-11095

**Comment by xstefank** [comment]
Thanks. I think you can close this issue now, the progress will be tracked in the JIRA you've created.
