### ISSUE TITLE
SAR jboss-service MBean start with @Postconstruct annotation called twice.

### ISSUE THREAD

**Issue by warrenc5** [wildfly/wildfly#11744]
Start and stop are "magic" method names for jboss services.
As a result the method is invoked twice.

I would expect the object has already started, so why call it again.
This is the same for Predestroy and stop() method.

In WFLYSRV0049: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) starting

@PostConstruct
public void start() {
        logger.info(this.hashCode() + "configuration for " + this.getBaseDir() + " " + System.getProperties().getProperty("jboss.server.config.dir"));
}

Output is 

(ServerService Thread Pool -- 69) 2034435521 configuration for /opt/wildfly/standalone/configuration /opt/wildfly/standalone/configuration
(ServerService Thread Pool -- 69) 2034435521 configuration for /opt/wildfly/standalone/configuration /opt/wildfly/standalone/configuration

**Comment by xstefank** [comment]
Hi @warrenc5, thank you for the report but we don't use GitHub issues for issue tracking. Can you create a ticket at https://issues.jboss.org/projects/WFLY/issues please?

**Comment by warrenc5** [comment]
Cheers, done.
https://issues.jboss.org/browse/WFLY-11190
