### ISSUE TITLE
error when creating a datasource via Management Console

### ISSUE THREAD

**Issue by Daniel-Dos** [wildfly/wildfly#11981]
I'm trying to create a datasource using  postgresql via GUI, but I always get this message:

```
10:29:01,462 ERROR [org.jboss.as.controller.management-operation] (External Management Request Threads – 2) WFLYCTL0013: Operation (“test-connection-in-pool”) failed - address: ([
(“subsystem” => “datasources”),
(“xa-data-source” => “PostgresXADS”)
]) - failure description: “WFLYJCA0040: failed to invoke operation: WFLYJCA0047: Connection is not valid”
```

now if I do using XA Datasource mode it works without problems.

This has happened to Wildfly 14 and 15.

**Comment by darranl** [comment]
For assistance please follow the link to the user forums to discuss the issues you are experiencing http://wildfly.org/gethelp/
