### ISSUE TITLE
Error with cors pre flight, header are correctly set but the server respond with 401

### ISSUE THREAD

**Issue by Gamdolf** [wildfly/wildfly#12023]
[config WF.txt](https://github.com/wildfly/wildfly/files/2783504/config.WF.txt)
Hi , 

I found a lot of similar issue tagged as closed but no one resolved... 

I have to set-up CORS on wildfly and for simple request every things is rigth. 

But when we have to deal with complex request this is always a fail. 

The server respond with a 401 on options request but all the header are set.

I need to match the CORS definition which says that on OPTIONS request the server shouldn't handle authentication. 

What is the correct way to handle this ? 

You can find below a request / response sample and the server configuration : 

_Request :_ 

Host: distantHost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: PUT
Access-Control-Request-Headers: x-bonita-api-token
Referer: http://currentHost/
Origin: http://currentHost
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

_Response :_ 

HTTP/1.1 401 Unauthorized
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
X-Powered-By: Undertow/1
Set-Cookie: SESSIONID=E7MEahqJVK0aNIp2GTdgoA02uS24ONeigJ779EKo.; path=/bonita
Access-Control-Allow-Headers: accept, authorization, content-type, x-requested-with, cache-control, x-bonita-api-token
Server: WildFly/10
Date: Tue, 22 Jan 2019 14:59:07 GMT
Connection: keep-alive
Access-Control-Allow-Origin: http://currentHost
Access-Control-Allow-Credentials: true
Content-Length: 0
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT

_Server Config :_ 

<subsystem xmlns="urn:jboss:domain:undertow:3.1">
	 <buffer-cache name="default"/>
	 <server name="default-server">
		 <http-listener name="default" socket-binding="http" redirect-socket="https" enable-http2="false" max-post-size="104857600" />
		 <https-listener name="https" socket-binding="https" security-realm="ApplicationRealm" enable-http2="false"/>
		 <host name="default-host" alias="localhost">
			 <location name="/" handler="welcome-content"/>
			 <access-log/>
			 <filter-ref name="server-header"/>
			 <filter-ref name="x-powered-by-header"/>
			 <filter-ref name="gzipFilter" predicate="exists('%{o,Content-Type}') and regex(pattern='(?:application/javascript|text/css|text/html|text/xml|application/json)(;.*)?', value=%{o,Content-Type}, full-match=true)"/>
			 <filter-ref name="Access-Control-Allow-Origin"/>
			 <filter-ref name="Access-Control-Allow-Methods"/>
			 <filter-ref name="Access-Control-Allow-Headers"/>
			 <filter-ref name="Access-Control-Allow-Credentials"/>
		 </host>
	 </server>
	 <servlet-container name="default">
		 <jsp-config tag-pooling="false"/>
		 <websockets/>
		 <session-cookie name="SESSIONID" />
	 </servlet-container>
	 <handlers>
		<file name="welcome-content" path="${jboss.home.dir}/welcome-content"/>
	 </handlers>
	 <filters>
		 <response-header name="server-header" header-name="Server" header-value="WildFly/10"/>
		 <response-header name="x-powered-by-header" header-name="X-Powered-By" header-value="Undertow/1"/>
		 <gzip name="gzipFilter"/>
		 <response-header name="Access-Control-Allow-Origin" header-name="Access-Control-Allow-Origin" header-value="http://currentHost"/>
		 <response-header name="Access-Control-Allow-Methods" header-name="Access-Control-Allow-Methods" header-value="GET, POST, OPTIONS, PUT"/>
		 <response-header name="Access-Control-Allow-Headers" header-name="Access-Control-Allow-Headers" header-value="accept, authorization, content-type, x-requested-with, cache-control, x-bonita-api-token"/>
		 <response-header name="Access-Control-Allow-Credentials" header-name="Access-Control-Allow-Credentials" header-value="true"/>
		 <response-header name="Cache-Control" header-name="Cache-Control" header-value="no-cache "/>
	 </filters>
</subsystem>

**Comment by Gamdolf** [comment]
<subsystem xmlns="urn:jboss:domain:undertow:3.1">
	 <buffer-cache name="default"/>
	 <server name="default-server">
		 <http-listener name="default" socket-binding="http" redirect-socket="https" enable-http2="false" max-post-size="104857600" />
		 <https-listener name="https" socket-binding="https" security-realm="ApplicationRealm" enable-http2="false"/>
		 <host name="default-host" alias="localhost">
			 <location name="/" handler="welcome-content"/>
			 <access-log/>
			 <filter-ref name="server-header"/>
			 <filter-ref name="x-powered-by-header"/>
			 <filter-ref name="gzipFilter" predicate="exists('%{o,Content-Type}') and regex(pattern='(?:application/javascript|text/css|text/html|text/xml|application/json)(;.*)?', value=%{o,Content-Type}, full-match=true)"/>
			 <filter-ref name="Access-Control-Allow-Origin"/>
			 <filter-ref name="Access-Control-Allow-Methods"/>
			 <filter-ref name="Access-Control-Allow-Headers"/>
			 <filter-ref name="Access-Control-Allow-Credentials"/>
		 </host>
	 </server>
	 <servlet-container name="default">
		 <jsp-config tag-pooling="false"/>
		 <websockets/>
		 <session-cookie name="SESSIONID" />
	 </servlet-container>
	 <handlers>
		<file name="welcome-content" path="${jboss.home.dir}/welcome-content"/>
	 </handlers>
	 <filters>
		 <response-header name="server-header" header-name="Server" header-value="WildFly/10"/>
		 <response-header name="x-powered-by-header" header-name="X-Powered-By" header-value="Undertow/1"/>
		 <gzip name="gzipFilter"/>
		 <response-header name="Access-Control-Allow-Origin" header-name="Access-Control-Allow-Origin" header-value="http://currentHost"/>
		 <response-header name="Access-Control-Allow-Methods" header-name="Access-Control-Allow-Methods" header-value="GET, POST, OPTIONS, PUT"/>
		 <response-header name="Access-Control-Allow-Headers" header-name="Access-Control-Allow-Headers" header-value="accept, authorization, content-type, x-requested-with, cache-control, x-bonita-api-token"/>
		 <response-header name="Access-Control-Allow-Credentials" header-name="Access-Control-Allow-Credentials" header-value="true"/>
		 <response-header name="Cache-Control" header-name="Cache-Control" header-value="no-cache "/>
	 </filters>
</subsystem>

**Comment by Gamdolf** [comment]
Xml config is hidden by github ...i'll join a file

**Comment by darranl** [comment]
For assistance please follow the link to the user forums to discuss the issues you are experiencing http://wildfly.org/gethelp/
