### ISSUE TITLE
SecurityContext Unsatisfied dependencies for type SecurityContext 

### ISSUE THREAD

**Issue by khaledabderrahim** [wildfly/wildfly#12034]
wildfly 15 .0.1
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type SecurityContext with qualifiers @Default

injecting SecurityContext in RequestScoped bean 

`
@Model
public class LoginBean {

    @Inject
    private SecurityContext securityContext;
}
`

jboss-web xml descriptor 
`<?xml version="1.0"?>
<jboss-web>
    <security-domain>jaspitest</security-domain>
</jboss-web>`

beans cdi xml descriptor 
`<beans
	xmlns="http://xmlns.jcp.org/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
	version="1.2"
	bean-discovery-mode="all">
</beans>`
the standalone.xml contains

`<subsystem xmlns="urn:jboss:domain:ee-security:1.0"/>
<security-domain name="jaspitest" cache-type="default">
                    <authentication-jaspi>
                        <login-module-stack name="dummy">
                            <login-module code="Dummy" flag="optional"/>
                        </login-module-stack>
                        <auth-module code="Dummy"/>
                    </authentication-jaspi>
                </security-domain>
`
the same problem alson on wildfly 13

**Comment by darranl** [comment]
For assistance please follow the link to the user forums to discuss the issues you are experiencing http://wildfly.org/gethelp/
