### ISSUE TITLE
ServiceSupplier and memory leak

### ISSUE THREAD

**Issue by andrew--i** [wildfly/wildfly#12170]
Hi!
I need help
15.0.x branch
wildfly/clustering/service/src/main/java/org/wildfly/clustering/service/ServiceSupplier.java#get

       

        ServiceName name = this.name.append(UUID.randomUUID().toString());
        ServiceBuilder<?> builder = target.addService(name);
        Supplier<T> supplier = builder.requires(this.name);
        ServiceController<?> controller = builder.setInitialMode(this.mode).install();

What is the service created for with the name this.name.append (UUID.randomUUID().toString())?

And why is it not removed from the org.jboss.msc.service.ServiceContainerImpl.registry?

**Comment by darranl** [comment]
For assistance please follow the link to the user forums to discuss the issues you are experiencing http://wildfly.org/gethelp/
