### ISSUE TITLE
Vault configration does not work in domain mode.

### ISSUE THREAD

**Issue by MrBalonio** [wildfly/wildfly#7215]
I am trying to mask passwords in a domain configuration. After following this tutorial https://github.com/wildfly/quickstart/tree/master/security-vault-askpass

and plaing the vault xml tags in the domain.xml I get the following error:

[Host Controller] 17:13:19,898 ERROR [org.jboss.as.host.controller] (Controller Boot Thread) JBAS010932: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: JBAS014676: Failed to parse configuration
[Host Controller]       at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:112) [wildfly-controller-8.1.0.Final.jar:8.1.0.Final]
[Host Controller]       at org.jboss.as.host.controller.DomainModelControllerService.boot(DomainModelControllerService.java:509) [wildfly-host-controller-8.1.0.Final.jar:8.1.0.Final]
[Host Controller]       at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:256) [wildfly-controller-8.1.0.Final.jar:8.1.0.Final]
[Host Controller]       at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_67]
[Host Controller] Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[34,9]
[Host Controller] Message: JBAS014789: Unexpected element '{urn:jboss:domain:2.1}vault' encountered
[Host Controller]       at org.jboss.as.controller.parsing.ParseUtils.unexpectedElement(ParseUtils.java:85) [wildfly-controller-8.1.0.Final.jar:8.1.0.Final]

does vault configuration no work in domain mode (domain.xml)?

Thanks

**Comment by ctomc** [comment]
For discussions like this please use forums https://developer.jboss.org/en/wildfly or if you find confirmed bug report it in jira https://issues.jboss.org/browse/WFLY
