### ISSUE TITLE
wildfly 8.2 cpu usage with jdk8

### ISSUE THREAD

**Issue by MohsenK** [wildfly/wildfly#7226]
Hi
i use wildfly 8.2 in my digitalocean vps with 2 virtual core and 1 GB ram.
but sometimes memory usages of wildfly is too high and dosen't respond to request and sometimes crash my VPS.
most of times is cpu usages of wildfly is normal ( from 10 to 20 percent ).
in first i use wildfly 8.1 i get proken pipe exception then apply 8.2 patch and exception fixed but there are cpu usage problem.
What is problem ?
Thanks.

**Comment by ctomc** [comment]
For discussions like this please use forums https://developer.jboss.org/en/wildfly or if you find confirmed bug report it in jira https://issues.jboss.org/browse/WFLY
