### ISSUE TITLE
How to improve error reporting in Java EE 

### ISSUE THREAD

**Issue by marouaMissaoui** [wildfly/wildfly#7263]
I don't know if Java ee 7 adopters ,Wildfly in particular, are with the same opinion about error reporting during deployment?!!! I find the messages literally unhelpful , unclear and the stack traces don't contain any clue.

**Comment by chenrui333** [comment]
[on-hold stackoverflow link](http://stackoverflow.com/questions/29125757/how-to-improve-error-reporting-in-java-ee-7)

**Comment by ctomc** [comment]
For discussions like this please use forums https://developer.jboss.org/en/wildfly or if you find confirmed bug report it in jira https://issues.jboss.org/browse/WFLY
