### ISSUE TITLE
HTTP API support for plain JBoss-CLI commands

### ISSUE THREAD

**Issue by jairojunior** [wildfly/wildfly#7527]
I've been working on a Puppet Module for Wildfly [1] that uses his HTTP Management API to perform operations (manage resources/deploys and execute commands), but my command execution code is a little bit limited cause I have to transform from CLI syntax to JSON. e.g.:

`:shutdown(restart=true)`

becomes

{"operation" : "shutdown", "restart" : "true" }  

Is there any specific reason to not support plain CLI commands through HTTP API? I looked at the code and it didn't see hard to implement this...

[1] https://github.com/biemond/biemond-wildfly

**Comment by ctomc** [comment]
Hi @jairojunior we don't use github issues(we must have them enabled for some automation tasks on PRs). 
For reporting bugs we use Jira https://issues.jboss.org/browse/WFLY
but for discussions like this more appropriate forum would be developer mailing list.
https://lists.jboss.org/mailman/listinfo/wildfly-dev so please send mail to mailing list where you are more likely to get response.
