### ISSUE TITLE
Java Agent Dependency With Shared Library 

### ISSUE THREAD

**Issue by pratikpparikh** [wildfly/wildfly#7753]
Dear Authors,

For the components that use Java Agent as a mean to weave classes for instrumentation, light weight threading or attack detection, on and on; those components may have lots of dependencies and since with Wildfly everything is a module or global module if shared across blue print. But this global module are not not available on a class path which makes it safe for multi tenancy at module level and resilient. Can WildFly make it easier for Java Agent to use the global modules as well?  Because currently the java agent in this case require a fat jar creation of every class that it calls and even though the module is available globally it won't use it as it is not on the class path or within the fat jar.

Regards,
Pratik Parikh

**Comment by jaikiran** [comment]
I'm not sure what you are asking, but this isn't where questions about WildFly are answered. A better place to ask the question is in the community forums at https://developer.jboss.org/en/wildfly

**Comment by pratikpparikh** [comment]
Based you in your require here is more detailed clear explanation I feel this is going to be an enhancement but I will greatly appreciate if you can provide me an workaround option that does not involve fat jar of all the dependency.
