### ISSUE TITLE
Two persistence.xml in two EJB projects within one EAR don't work

### ISSUE THREAD

**Issue by Hades32** [wildfly/wildfly#7801]
We're in the progress of migrating to Wildfly but it doesn't seem to support our current setup.

I created a repro at https://github.com/Hades32/wildfly-issues

Wildfly doesn't seem to be able to resolve dependencies between modules as soon as there are two persistence.xml's. Despite the (repro) project doesn't even use it (yet). If you remove the persistence.xml's the project works fine.

This was tested with Wildfly 9.0 Final

**Comment by jamezp** [comment]
Hello. Please ask questions like this on forums, https://developer.jboss.org/en/wildfly. For issues we file them in JIRA at https://issues.jboss.org/browse/WFLY/. Thanks!

**Comment by Hades32** [comment]
done https://developer.jboss.org/thread/261445
