### ISSUE TITLE
Context-Root of WAR cannot be changed if WAR is not in root of EAR

### ISSUE THREAD

**Issue by Hades32** [wildfly/wildfly#7808]
Working example: (snippets from META-INF/application.xml in an EAR)
```
  <module id="wftest.server-wftest.server.backend.web">
    <web>
      <web-uri>wftest.server-wftest.server.backend.web-1.31.0-buildr.war</web-uri>
      <context-root>/eu/backend</context-root>
    </web>
  </module>
```
NOT working example: (the WAR file was moved into /war of course beforehand)
```
  <module id="wftest.server-wftest.server.backend.web">
    <web>
      <web-uri>war/wftest.server-wftest.server.backend.web-1.31.0-buildr.war</web-uri>
      <context-root>/eu/backend</context-root>
    </web>
  </module>
```
The second form is the default of what buildr (https://buildr.apache.org/packaging.html#ear) produces. It can be worked around with something like `, :path=>''`, but why the limitation?

Tested with Wildfly 9.0 Final

**Comment by jamezp** [comment]
Hello. Please ask questions like this on forums, https://developer.jboss.org/en/wildfly. For issues we file them in JIRA at https://issues.jboss.org/browse/WFLY/. Thanks!

**Comment by Hades32** [comment]
done https://developer.jboss.org/thread/261444
