### ISSUE TITLE
Is it ok to use Java 7 or later in ConcurrentReferenceHashMap.java?

### ISSUE THREAD

**Issue by alexVengrovsk** [wildfly/wildfly#8030]
If it is ok to use Java 7 or higher in ```ConcurrentReferenceHashMap.java```, there are some possibilities for improvement and minimisation of verbosity.

**Comment by ctomc** [comment]
We don't use github issues.
You should ether use mailing list, user forums or file jira report if you found bug.
see http://wildfly.org/gethelp/ for details where to get hold of team.

**Comment by alexVengrovsk** [comment]
@ctomc  Thank you.
