### ISSUE TITLE
Wrong number of message on queue

### ISSUE THREAD

**Issue by abdollahpour** [wildfly/wildfly#8079]
I'm getting wrong number of message on queue here:

    Server: Standalone Server > Monitor: Subsystems > Subsystem: JMS Destinations

    Queue Metrics
        Consumer Count	0
        Message Count	-1959
        Messages Added	15259
        Scheduled Count	0

It happens after several undeploy deploy my app. The app is working normal but I need to have right number of messages on queue.

**Comment by ctomc** [comment]
We don't use github issues.
You should ether use mailing list, user forums or file jira report if you found bug.
see http://wildfly.org/gethelp/ for details where to get hold of team.
