### ISSUE TITLE
23 character length limitation on node identifier

### ISSUE THREAD

**Issue by derek63** [wildfly/wildfly#8271]
Does the character limitation on the node identifier in the transactions subsystem still need to be only 23 characters?  

https://github.com/wildfly/wildfly/blob/master/transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemRootResourceDefinition.java#L95

I just (accidentally) ran into this error when specifying a value longer than 23 characters, and was curious about the origin of this specific limitation, and whether or not it could/should be increased.

**Comment by rhusar** [comment]
See https://issues.jboss.org/browse/AS7-5135?focusedCommentId=12705161&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12705161
