### ISSUE TITLE
Wildfly 10.RC4 modcluster load balancing error

### ISSUE THREAD

**Issue by sunchanras** [wildfly/wildfly#8398]
I set up Wildfly 10.rc4 load balancing follow https://github.com/stuartwdouglas/modcluster-example .
It worked just fine until I set app context to "/" in jboss-web.xml

Here is the error messages I got.
```
MODCLUSTER000042:Error null sending info command to 127.0.0.1....
```
Best Regard,
Sun Chanras

**Comment by jamezp** [comment]
Hello. We don't use the GitHub issues. If you have a question feel free to ask on [HipChat](https://www.hipchat.com/gW90m6pIs), IRC or in the [forums](https://developer.jboss.org/en/wildfly).
