### ISSUE TITLE
use of env: in powershell scripts

### ISSUE THREAD

**Issue by HenkNijveld** [wildfly/wildfly#8641]
In the powershell scripts is the use of environment variables. To use one the syntax is:
$env:environment name. example  $env:JAVA_OPTS.
In the current deliverd scripts the $ sign is missing in the use of the envirnonment variables. example line in the current common.ps1: (line 20)
```
    if( Test-Path env:$key ) {
```
This should be changed to
```
    if( Test-Path $env:key ) {
```

**Comment by langfr** [comment]
github issue feature is not used in this project, report the problem you found at https://issues.jboss.org/browse/WFLY/.

**Comment by ctomc** [comment]
As @langfr said, we dont use github issues for issue tracking.

But in any case, construct if ( Test-Path env:JAVA_HOME) is correct one.
you don't need $env when testing for existence as Test-Path uses "env" variable already.
our full construct is (Test-Path env:$key ) as we are dynamically testing for different keys if they are present.

**Comment by HenkNijveld** [comment]
try in powershell: 
```
Write-Host env:JAVA_HOME
Write-Host $env:JAVA_HOME
```
The first one does not resolve to a value. So you can't use it

But I agree that there are more improvents to make. I will create a JIRA account, and create an issue there, and try to improve the powershell scripts.

**Comment by ctomc** [comment]
Well try this

if ( Test-Path env:JAVA_HOME) { 
  Write-Host $env:JAVA_HOME 
}

and you will see it correctly print JAVA_HOME as it is defined.
