### ISSUE TITLE
init.d script works incorretct while domain starting

### ISSUE THREAD

**Issue by va1m** [wildfly/wildfly#8664]
The `wildlfy` startup script located in the `/etc/init.d` folder returns control earlier then domain starts.
Look at this part of the script:
```
until [ $count -gt $STARTUP_WAIT ]
        do
                grep 'WFLYSRV0025:' $JBOSS_CONSOLE_LOG > /dev/null
                if [ $? -eq 0 ] ; then
                        launched=true
                        break
                fi
                sleep 1
                let count=$count+1;
        done
```
It search a message "WFLYSRV0025:" while server starts. But while domain starting there are the message occurs three times - for `Host controller`, `server-one` and `server-two`.

**Comment by va1m** [comment]
Seems like wildfly startup script has been removed from WF10.

**Comment by ctomc** [comment]
1) scripts ware just moved to docs/contrib
2) in case of domain controller only message that is relevant is that domain controller (host controller)
as domain/host controller can be started without any servers at all, so monitoring for all servers to be up is futile and wrong.
