### ISSUE TITLE
Which version of Wildly support  Java 8 ?

### ISSUE THREAD

**Issue by sbose78** [wildfly/wildfly#8769]
I see that EAP 6.3.3 has added support for IBM Java 8.
https://access.redhat.com/articles/111663

Does Wildfly 8 support IBM Java 8 ? Is there some documentation around the support matrix?

Thanks,
Shoubhik

**Comment by rhusar** [comment]
See https://access.redhat.com/documentation/en/red-hat-jboss-enterprise-application-platform/version-7.0.beta/700-beta-release-notes/

> Java SE 8 JBoss EAP 7 requires Java SE 8, and JBoss EAP 7 Beta has been tested with Open JDK 8, Oracle JDK 8.

**Comment by ctomc** [comment]
WildFly 8.x is the first to support JDK8. But using newer versions is always better
