### ISSUE TITLE
Performance: WeldDeployment.getBeanDeploymentArchive method is synchronized

### ISSUE THREAD

**Issue by pgrigoro** [wildfly/wildfly#8777]
(Wildfly 10.0.0.FINAL)
During the performance test of my app (50 concurrent users with jmeter) I am running into the following issue:
There are locked threads in the method WeldDeployment.getBeanDeploymentArchive(). Looking the code, this method is synchronized, so it makes sense. The question is, is this the expected behavior or this is a bug. In both cases is there any workaround to overcome this limitation?

STACK TRACE:
....
org.jboss.as.weld.WeldProvider$CdiImpl.getBeanManager():73
org.jboss.as.weld.WeldProvider$CdiImpl.getBeanManager():93
org.jboss.as.weld.deployment.WeldDeployment.getBeanDeploymentArchive():226

**Comment by pgrigoro** [comment]
Is this planned for the next release?

**Comment by ctomc** [comment]
we do not use github issues for our bug tracker, use jira for that https://issues.jboss.org/browse/WFLY
