### ISSUE TITLE
Fix POJO super method not found

### ISSUE THREAD

**Issue by lpenczek** [wildfly/wildfly#8856]
Using a method defined in a superclass for a POJO defined by a
jboss-beans.xml, such as , where create is a
method defined in the superclass of the POJO, results in method not
found exception.
This occurs because the initial value (classInfo) is used inside the
while-loop, instead of the current value (current).
This bug prevents inheritance for POJOs.

Fix for this problem org.jboss.as.pojo.service.Configurator line 180:
Change this:
ClassReflectionIndex cri = index.getClassIndex(classInfo);
to this:
ClassReflectionIndex cri = index.getClassIndex(current);

**Comment by ctomc** [comment]
we do not use github for issue tracking but jira at https://issues.jboss.org/browse/WFLY
