### ISSUE TITLE
Fix big jboss-beans.xml files truncation

### ISSUE THREAD

**Issue by lpenczek** [wildfly/wildfly#8857]
If the jboss-beans.xml file is big enough, truncation may occur in the value of a property.

Fix for this problem:

In the org.jboss.as.pojo.KernelDeploymentParsingProcessor constructor, add this line of code:
inputFactory.setProperty("javax.xml.stream.isCoalescing", Boolean.valueOf(true));

It prevents the truncation.

**Comment by ctomc** [comment]
we do not use github for issue tracking but jira at https://issues.jboss.org/browse/WFLY
but you are welcome to send pull request with a fix.
