### ISSUE TITLE
How to integrate mybatis to wildfly ?

### ISSUE THREAD

**Issue by slieer** [wildfly/wildfly#8974]
[Mybatis](https://github.com/mybatis/mybatis-3) simple, lightweight, more popular than hibernate. Please give official support.

**Comment by langfr** [comment]
First of all, the right place for feature requests is https://issues.jboss.org/projects/WFLY/issues/.
But before it's recommended to discuss your request at https://developer.jboss.org/en/wildfly/content/.
I doubt your statement that mybatis is more popular than hibernate and in my eyes, you're comparing apples with oranges. In my eyes and also for others, mybatis is not a ORM like Hibernate is.
And mybatis does not implement JPA, so it cannot be an alternative to Hibernate.
But you can use mybatis in your application or module just fine. I'm using Camunda BPM, which uses mybatis for persistence, as a wildfly module from my application.

**Comment by slieer** [comment]
see https://developer.jboss.org/message/959123#959123
