### ISSUE TITLE
How come access logs display a '-' when I'm trying to print out %T of access log

### ISSUE THREAD

**Issue by zmhassan** [wildfly/wildfly#9015]
I'm running wildfly 10 and trying to get the response time of web service calls into my access log
Doing some googling looks like like others have run into this too:
`https://issues.jboss.org/browse/UNDERTOW-159`

On that jira someone is suggesting to use this property for undertow:
`...
You need to add the record-request-start-time="true" attribute to the connector.`

Correct me if I'm wrong. I don't think this property is available in standalone.xml Is it possible to use that in standalone.xml?

**Comment by ctomc** [comment]
We do not use github for issue tracking but jira https://issues.jboss.org/browse/WFLY
or for questions like this use forums at https://developer.jboss.org/en/wildfly
