### ISSUE TITLE
JCA on WF 10: TCP IP closes every 45 mins

### ISSUE THREAD

**Issue by napster68** [wildfly/wildfly#9073]
Hi
 
I have a resource adapter that is implemented by SocketConnector - https://bitbucket.org/__jtalk/socketconnector/issues/5/socketconnector-timing-out-after-every
 
It seems like WF10 is initiating a disconnect every 45mins. How do I stop this from happening? Is there an entry I need to make in my standalone-full.xml and under which subsystem?
 
 
thanks,
Daslan

**Comment by ctomc** [comment]
we do not use github issues for bug tracking. but jira https://issues.jboss.org/browse/WFLY
for discussions like this we use forums, where you already posted https://developer.jboss.org/message/960597 so all you can do is wait for response there. Keep in mind that it is summer time and not everyone is in front of their computers.
