### ISSUE TITLE
error in wildfly-parent pom

### ISSUE THREAD

**Issue by reitzmichnicht** [wildfly/wildfly#9221]
The wildfly-parent pom manages a dependency with a nonexisting version:
 <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-search-analyzers</artifactId>
                <version>${version.org.hibernate.search}</version>
            </dependency>

This leads to errors for example with maven owasp check plugin.

**Comment by ctomc** [comment]
wildfly-parent pom is not meant to be used outside of WildFly build.
if you need user boms take a look at https://github.com/wildfly/boms
