### ISSUE TITLE
Issue while compiling the code

### ISSUE THREAD

**Issue by nageshever** [wildfly/wildfly#9328]
Getting an issue while compiling the Jboss AS 7.2.0 label code. Same with 7.1.1 as well. Attached is the exception.

[org.jboss.as.clustering.web.infinispan.DistributedCacheManagerTest.txt](https://github.com/wildfly/wildfly/files/567999/org.jboss.as.clustering.web.infinispan.DistributedCacheManagerTest.txt)

Can someone please respond.

**Comment by langfr** [comment]
Please use the forum at https://developer.jboss.org/en/jbossas7/content/ and close this issue.
Provide more information about
- platform (OS: Windows x, Linux, ...)
- compiler (Oracle JDK xxx or else?, Version?)
- the comman you used to start the compile / test

**Comment by nageshever** [comment]
Thank you for your response. Below is my response to your questions. I will close and open a forum thread.

platform (OS: Windows x, Linux, ...) - Windows
compiler (Oracle JDK xxx or else?, Version?) Oracle JDK, 1.7.0_55
the comman you used to start the compile / test - As per the documentation in github, I have used build.bat
