### ISSUE TITLE
New infinispan 8.2.4 and jboss-as-infinispan_4_0.xsd incompatibility

### ISSUE THREAD

**Issue by vladimiravramov** [wildfly/wildfly#9447]
New infinispan version in WF 10.1.0.Final doesn't have `max-entries` attribute for `eviction`,
but it's present in xsd. Is it a mistake in the scheme?

**Comment by pferraro** [comment]
The Infinispan subsystem schema in WF != Infinispan's native XML schema.
So, no - it is not a mistake.

**Comment by vladimiravramov** [comment]
Paul, thank you for your answer!
Could you please, explain me how can I setup named cache via 
Infinispan subsystem then WF using old scheme and new version of Infinispan
with new version of xsd for settings? Perhaps I'm on wrong way...
I'm trying to setup named cache (using Infinispan WF subsystem) 
and set `size` parameter for `eviction`,  but WF can't start with this parameter 
(because xsd-validation failed). With old parameter `max-entries` Infinispan doesn't
understand it this parameter.

**Comment by pferraro** [comment]
"With old parameter max-entries Infinispan doesn't understand this parameter"
What evidence do you have that this is the case?

**Comment by vladimiravramov** [comment]
> What evidence do you have that this is the case?

I can see it in the Infinispan cache statistics.
Also I can see by debugging 
`org.hibernate.cache.infinispan.InfinispanRegionFactory#createCacheManager(java.util.Properties, org.hibernate.service.ServiceRegistry)`
when I'm trying to add 2LC for Hibernate and read all named cache configuration
from Infinispan subsystem.
I think it's normal behavior: I'm setupping config for Infinispan (it's Final 8.2.4 version) with
inappropriate configuration and without any config-bridge it's not possible to pass
right parameters, isn't it?

**Comment by pferraro** [comment]
"org.hibernate.cache.infinispan.InfinispanRegionFactory" doesn't use configuration from the Infinispan subsystem.  I suggest you use the region factory implementations shipped by WildFly, which are designed to use cache managers that are managed and configured via the Infinispan subsystem.

**Comment by vladimiravramov** [comment]
> I suggest you use the region factory implementations shipped by WildFly, which are designed to use cache managers that are managed and configured via the Infinispan subsystem.

I'm using `org.jboss.as.jpa.hibernate5.infinispan.SharedInfinispanRegionFactory` which get
hibernate cache manager by default from Infinispan subsystem. SharedInfinispanRegionFactory derrived from InfinispanRegionFactory as I can see.

**Comment by pferraro** [comment]
You previously stated that you saw this while debugging
"org.hibernate.cache.infinispan.InfinispanRegionFactory#createCacheManager(java.util.Properties, org.hibernate.service.ServiceRegistry)", however  this method is overridden by SharedInfinispanRegionFactory, which does not call the super implementation - so I'm a bit confused.
Can you post some log messages or CLI output that indicates the issue that you are talking about?  because, otherwise, I do not see it.

**Comment by vladimiravramov** [comment]
Sorry, It's my mistake in code example:
I can see it in `ru.gov.fms.umms.jipijapa.infinispan.InfinispanRegionFactory#start`
Ok. For instance, we have named config in subsystem settings and hibernate.cache.region_prefix = "infinispan":
`<subsystem xmlns="urn:jboss:domain:infinispan:4.0">

            <cache-container name="hibernate" default-cache="infinispan.ImmutableEntity" module="org.hibernate.infinispan" statistics-enabled="true">
                <local-cache name="local-query" statistics-enabled="true">
                    <eviction strategy="LRU" max-entries="50000"/>
                    <expiration interval="1000000" max-idle="600000"/>
                </local-cache>
            </cache-container>
        </subsystem>`
After manager creation we have overrided "max-entries" attribute for default JPA regions (
entity, collection, timestamp and etc) in `initGenericDataTypeOverrides`, but for another named
region attribute "max-entries" is used "as is". As I understand it's possible to override named
region for JPA in persistence.xml. Ok. But if I use non-jpa cache how can I set eviction attribute
for Infinispan module which expect "size" attribute instead deprecated and deleted "max-entries"?

**Comment by pferraro** [comment]
Can you paste your persistence.xml?

**Comment by vladimiravramov** [comment]
<persistence-unit name="infinispanTest">
		<provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
		<jta-data-source>jdbc/infinispanTest</jta-data-source>
		<shared-cache-mode>ENABLE_SELECTIVE</shared-cache-mode>
		<properties>
			<property name="hibernate.dialect" value="ru.gov.fms.umms.domain.OracleDialect" />
			<property name="hibernate.max_fetch_depth" value="0" />
			<property name="hibernate.jdbc.batch_size" value="0" />
			<property name="hibernate.statement_cache.size" value="0" />
			<property name="hibernate.jdbc.wrap_result_sets" value="true" />
			
			<property name="hibernate.cache.use_structured_entries" value="true" />
			<property name="hibernate.cache.use_second_level_cache" value="true" />
			<property name="hibernate.cache.use_query_cache" value="true" />
			
			<property name="hibernate.cache.region.factory_class" value="org.hibernate.cache.infinispan.JndiInfinispanRegionFactory"/>
			<property name="hibernate.cache.infinispan.cachemanager" value="java:jboss/infinispan/container/hibernate" />
			<property name="hibernate.jdbc.use_get_generated_keys" value="true" />
			<property name="hibernate.cache.region_prefix" value="infinispan" />
		</properties>
	</persistence-unit>

**Comment by pferraro** [comment]
You are giving me conflicting information.  You told me:

> I'm using org.jboss.as.jpa.hibernate5.infinispan.SharedInfinispanRegionFactory


however your persistence.xml indicates otherwise:
```xml
<!--Infinispan configuration-->
<property name="hibernate.cache.region.factory_class" value="org.hibernate.cache.infinispan.JndiInfinispanRegionFactory"/>
<property name="hibernate.cache.infinispan.cachemanager" value="java:jboss/infinispan/container/hibernate" />
```

**Comment by vladimiravramov** [comment]
Yep, your're right. I've switched my test project to JndiInfinispanRegionFactory (and send to you as is), but not working. As I can see both factory use "hibernate" as default container and result will be  identical.....

**Comment by pferraro** [comment]
JndiInfinispanRegionFactory is not a supported in WildFly.  Why you are overriding the default region factory used by WildFly?

**Comment by vladimiravramov** [comment]
> Why you are overriding the default region factory used by WildFly?

[I found this in the documentation](https://docs.jboss.org/author/display/WFLY10/JPA+Reference+Guide#JPAReferenceGuide-UsingtheInfinispansecondlevelcache)

**Comment by pferraro** [comment]
Nothing in that document suggests using JndiInfinispanRegionFactory.

**Comment by vladimiravramov** [comment]
I don't use JndiInfinispanRegionFactory. I use only SharedInfinispanRegionFactory.
My original persistance.xml: 
```
<persistence-unit name="infinispanTest">
	<provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
	<jta-data-source>jdbc/infinispanTest</jta-data-source>
	<shared-cache-mode>ENABLE_SELECTIVE</shared-cache-mode>
	<properties>
		<property name="hibernate.dialect" value="ru.gov.fms.umms.domain.OracleDialect" />
		<property name="hibernate.max_fetch_depth" value="0" />
		<property name="hibernate.jdbc.batch_size" value="0" />
		<property name="hibernate.statement_cache.size" value="0" />
		<property name="hibernate.jdbc.wrap_result_sets" value="true" />
		<!-- 2nd level cache -->
		<property name="hibernate.cache.use_structured_entries" value="true" />
		<property name="hibernate.cache.use_second_level_cache" value="true" />
		<property name="hibernate.cache.use_query_cache" value="true" />
		<!--Infinispan configuration-->
		<property name="hibernate.cache.region.factory_class" value="org.jboss.as.jpa.hibernate5.infinispan.SharedInfinispanRegionFactory"/>
		<property name="hibernate.cache.infinispan.cachemanager" value="java:jboss/infinispan/container/hibernate" />
		<property name="hibernate.jdbc.use_get_generated_keys" value="true" />
		<property name="hibernate.cache.region_prefix" value="infinispan" />
	</properties>
</persistence-unit>
```

**Comment by pferraro** [comment]
Don't try to name your cache configurations using the region_prefix.  The configuration of a given region cache is based on a specific cache configuration name per region type.  The default hibernate cache configuration uses the cache configuration names per region type that the default region factory expects.  If you really want to override the default cache configuration names for a given region type, you need to specify this explicitly in your persistence.xml.  See: https://docs.jboss.org/author/display/ISPN/Using+Infinispan+as+JPA-Hibernate+Second+Level+Cache+Provider#UsingInfinispanasJPA-HibernateSecondLevelCacheProvider-AdvancedConfiguration

N.B. You can omit the "hibernate.cache.region.factory_class" property, since you are using the default region factory.

N.B. `<property name="hibernate.cache.infinispan.cachemanager" value="java:jboss/infinispan/container/hibernate" />` is not used by SharedInfinispanRegionFactory.  This impl does not use JNDI to locate the cache container.  Instead, the cache container is identified by name via the "hibernate.cache.infinispan.container" property and defaults to "hibernate".

**Comment by vladimiravramov** [comment]
Paulo, thanks a lot for you answer!
As I understand where's no way to override named cache configuration via Infinispan
subsystem. Is it true? 
If I have entity
```
@Entity
@Immutable
@Table(name = "TABLE")
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY, region = "ImmutableEntity")
public class HugeImmutableEntity {
.....
}
```

Can I override 2LC setting for **ImmutableEntity** region 
via WF Infinispan subsystem (without persistence.xml)?

**Comment by pferraro** [comment]
@vladimiravramov Yes, you can specify the following in your persistence.xml to override the cache configuration used for a given cache region:
`<property name="hibernate.cache.infinispan.[region-name].cfg" value="[cache-name]"/>`

**Comment by vladimiravramov** [comment]
> (without persistence.xml)

Is it possible with Infinispan subsystem ?

**Comment by pferraro** [comment]
@vladimiravramov Unless you override the cache configuration for a given region name in persistence.xml, the default cache configuration for the region type will be used.
