### ISSUE TITLE
hibernate.jdbc.time_zone property ignored

### ISSUE THREAD

**Issue by vbaidak** [wildfly/wildfly#9606]
Hi!

I've faced with an issue that in case of **JTA** transaction-type configuration, Hibernate's native property **hibernate.jdbc.time_zone** (org.hibernate.cfg.AvailableSettings.JDBC_TIME_ZONE) is ignored.

In case of **RESOURCE_LOCAL** transaction-type it is loaded correctly.

Is there any way to configure Hibernate/JPA timezone for JTA transaction type w/o code changes?
Thanks!

**Comment by ctomc** [comment]
please use forums for this kind of questions
https://developer.jboss.org/en/wildfly
or in this case even better probably 
https://forum.hibernate.org/
