### ISSUE TITLE
Wildfly with infinispan cache

### ISSUE THREAD

**Issue by angelorlcosta** [wildfly/wildfly#9673]
Hello all,

I am trying to use wildfly with infinispan cache and trying to persiste the cache in a mysql database.

Therefore configured a datasource:

		<datasource jta="false" jndi-name="java:jboss/datasources/DSMysql" pool-name="mysql" enabled="true" use-ccm="false">
                    <connection-url>jdbc:mysql://localhost:3306/test?autoReconnect=true&amp;useSSL=false</connection-url>
                    <driver-class>com.mysql.jdbc.Driver</driver-class>
                    <driver>mysql</driver>
                    <security>
                        <user-name>root</user-name>
                        <password>password</password>
                    </security>
                    <validation>
                        <valid-connection-checker class-name="org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker"/>
                        <validate-on-match>true</validate-on-match>
                        <background-validation>true</background-validation>
                    </validation>
                    <statement>
                        <share-prepared-statements>false</share-prepared-statements>
                    </statement>
                </datasource>

And then configured the distributed cache as per bellow:

                <distributed-cache name="TEST_DATA" owners="2" mode="ASYNC" segments="20" remote-timeout="300000">
                    <locking isolation="READ_UNCOMMITTED" striping="false" acquire-timeout="15000" concurrency-level="10000" />
                    <string-keyed-jdbc-store data-source="mysql" shared="true" preload="true" passivation="false" fetch-state="true" purge="false">
                        <write-behind modification-queue-size="8192" thread-pool-size="1000"/>
                        <string-keyed-table prefix="CACHE">
                            <id-column name="id" type="VARCHAR(100)"/>
                            <data-column name="datum" type="BLOB"/>
                            <timestamp-column name="version" type="BIGINT"/>
                        </string-keyed-table>
                    </string-keyed-jdbc-store>
                </distributed-cache>

But in the mysql database the table for this cache is not created when we startup the server.
I would expect a new table called CACHE_TEST_DATA to be created.

Any idea why?

Thanks in advance,
Ângelo Costa

**Comment by rhusar** [comment]
Hey. I am not seeing any of the configuration elements just random values thrown around, could you edit your post to show what you are actually configuring?

**Comment by angelorlcosta** [comment]
Hello,
I believe i have corrected the above text.

**Comment by chalzstrassen** [comment]
@angelorlcosta Your infinispan configuration does not contain any reference to the datasource you have defined. You should add a datasource tag like so:
```xml
<distributed-cache name="TEST_DATA" owners="2" mode="ASYNC" segments="20" remote-timeout="300000">
	<locking isolation="READ_UNCOMMITTED" striping="false" acquire-timeout="15000" concurrency-level="10000" />
	<string-keyed-jdbc-store data-source="mysql" shared="true" preload="true" passivation="false" fetch-state="true" purge="false">
                <data-source jndi-url="java:jboss/datasources/DSMysql" /> <!-- Added this line -->
		<write-behind modification-queue-size="8192" thread-pool-size="1000"/>
		<string-keyed-table prefix="CACHE">
			<id-column name="id" type="VARCHAR(100)"/>
			<data-column name="datum" type="BLOB"/>
			<timestamp-column name="version" type="BIGINT"/>
		</string-keyed-table>
	</string-keyed-jdbc-store>
</distributed-cache>
```
http://infinispan.org/docs/8.2.x/user_guide/user_guide.html#sample_configurations
