### ISSUE TITLE
WildFly 10 - How to change default encoding?

### ISSUE THREAD

**Issue by NiklasA** [wildfly/wildfly#9830]
Hi,

I have a question. How can I configure WildFly / Undertow to set UTF-8 as default response encoding?
I don't want to add ";charset=UTF-8" to every JAX-RS API therefore I am searching for a generic solution.

I ran these commands, but they don't have the right effect.
```
$WILDFLY_HOME/bin/./jboss-cli.sh --connect --command="/subsystem=undertow/servlet-container=default:write-attribute(name=use-listener-encoding,value=true)" > config.log 2>&1 &
$WILDFLY_HOME/bin/./jboss-cli.sh --connect --command="/subsystem=undertow/servlet-container=default:write-attribute(name=default-encoding,value=UTF-8)" > config.log 2>&1 &
```

Does anyone know, how can I fix this?

Thank you in advance.
Niklas

**Comment by ctomc** [comment]
Please use forums at https://developer.jboss.org/en/wildfly

**Comment by NiklasA** [comment]
@ctomc Thank you. I created a [discussion](https://developer.jboss.org/message/970246#970246).
