### ISSUE TITLE
ClassCastException due to wrong class loader after remote EJB invocation inside the same JVM

### ISSUE THREAD

**Issue by strohmattenverleger** [wildfly/wildfly#9990]
Hello,

I think I've discovered a bug in WildFly 10.1 regarding remote EJB invocations inside the same JVM.

When the caller uses an interface for a remote invocation which is part of a JBoss module instead of the calling Java EE module, WildFly tries to clone the entire return value object graph using the interface's JBoss module class loader instead of the Java EE module's class loader.

I've attached three Maven projects which reproduce the issue. To reproduce the issue just build the projects, deploy them (don't forget the JBoss module _generic-service-api_ which you can find pre-built inside the project's target directory), run your WildFly and open http://localhost:8080/b-service-war/my-entities/42 in a browser. You should get a `ClassCastException`.

I've also attached a patch which contains a fix. It actually contains two fixes:
* Using the Java EE module's class loader instead of the interface's JBoss module class loader
* Getting rid of the `LocalInvocationClassCloner`, because it has no upside, but a downside which is swallowing/hiding packaging issue

If you accept this issue, I'd be willing to commit a fix and create a pull request for you.

Regards

[projects.zip](https://github.com/wildfly/wildfly/files/968098/projects.zip)
[wildfly.patch.txt](https://github.com/wildfly/wildfly/files/968102/wildfly.patch.txt)

**Comment by ctomc** [comment]
any chance you can create pull request to this repo?

**Comment by ctomc** [comment]
I've created jira on your behalf https://issues.jboss.org/browse/WFLY-8907

**Comment by strohmattenverleger** [comment]
Hi, @ctomc,

thanks for creating the JIRA ticket.

I just wanted to give you a quick update: I'm currently working on an Arquillian-based test to verify the fix. It's working in my IDE but not as part of the Maven build, yet. I'll create a pull request as soon as I'm done with the test.

Regards

**Comment by strohmattenverleger** [comment]
Hi, @ctomc,

thanks for creating the JIRA ticket.

I just wanted to give you a quick update: I'm currently working on an Arquillian-based test to verify the fix. It's working in my IDE but not as part of the Maven build, yet. I'll create a pull request as soon as I'm done with the test.

Regards

**Comment by strohmattenverleger** [comment]
Hi, @ctomc,

I have created a pull request: https://github.com/wildfly/wildfly/pull/10184

Regards
